name: ebom
description: "A modern market place"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.10+1
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  path: ^1.9.0
  url_strategy: ^0.3.0
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.7
  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/i18n/
    - assets/images/
